[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timed = "0.2.1"
itertools = "0.12.0"

[profile.release]
strip = true
lto = "fat"
panic = 'abort'
codegen-units = 1
